# -*- coding: utf-8 -*-
"""Twitter v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AxuVw6Ju0IaMVWaBxqEavArQnLapAHB0

# Twitter
"""

pip install crewai==0.28.8 crewai_tools==0.1.6 langchain_community==0.0.29

!pip install numpy==1.26.4

from crewai import Agent, Task, Crew
from crewai_tools import tool
from IPython.display import Markdown
from crewai_tools import SerperDevTool, ScrapeWebsiteTool, WebsiteSearchTool

"""- As a LLM for your agents, you'll be using OpenAI's `gpt-3.5-turbo`.
\
"""

import openai

openai.api_key = "" #insert the Open API key

import os
#from utils import get_openai_api_key

#openai_api_key = get_openai_api_key()
import os
os.environ["OPENAI_API_KEY"] = "" #insert the Open API key
os.environ["OPENAI_MODEL_NAME"] = 'gpt-3.5-turbo'

import os
os.environ["SERPER_API_KEY"] = "" #insert the Server API key

#Twitter

from crewai import Agent, Task, Crew

# Agent 1: Tweet Strategist
tweet_agent = Agent(
    name='Tweet Strategist',
    role='Social Media Expert',
    goal="Write concise, punchy tweets that resonate with the target audience and encourage high engagement on {topic}",
    backstory="You are working to create a tweet on what is happening in {topic}.You're a seasoned twitter expert with a deep understanding of Twitter’s engagement dynamics. "
              "You specialize in distilling complex ideas into sharp, witty, or emotionally resonant tweets."
              "You work alongside the Hashtag & Trending Topic Analyst to make sure your tweets are discoverable, and your content serves "
              "Tweets are short posts that people share on X (formerly Twitter) — a social media platform. Purpose of tweet is to Share an idea, opinion, joke, news, or update, Start a conversation"
              "React to something happening in the world, Build a personal or business brand. Tweet can only be of 280 words"
              "Example of a simple text tweet: Don't wait for motivation. Build discipline. That's the real secret.",
    tools=[SerperDevTool(), ScrapeWebsiteTool()],
    allow_delegation=False,
    verbose=True
)


# Agent 2: Hashtag & Trending Topic Analyst
trend_agent = Agent(
    name='Hashtag & Trending Topic Analyst',
    role='Trend Analyst',
    goal= "Identify high-traffic hashtags to enhance the discoverability of tweets which have been creayed by Tweet Strategist",
    backstory="You're a data-savvy analyst who monitors Twitter's trending topics, niche conversations, and hashtag performance. "
              "You support the Tweet Strategist by ensuring their content aligns with trending themes and uses hashtags that maximize reach. "
              "Your insights shape the direction of tweets and threads for higher engagement and topical relevance.",
    allow_delegation=False,
    tools=[SerperDevTool(), ScrapeWebsiteTool()],
    verbose=True
)

# Task 1: Generate Concise Tweets
task_tweets = Task(
    description="Generate a concise, impactful tweet on a given topic that hooks readers and aligns with current engagement styles. Attach relevant links in the tweet.",
    agent=tweet_agent,
    expected_output="A concise and impactful tweet with relevant links.Tweet can only be of 280 words. Make sure the link is fucntional" # Added expected output
)


# Task 2: Hashtag & Trending Topic Analysis
task_trending = Task(
    description="Analyze Twitter trends and suggest relevant hashtags and themes that can be incorporated into the tweets and threads "
    "for the tweets created by tweet agent",
    agent=trend_agent,
    expected_output="A tweet and thread on the given topic with relevant hashtags.Hastags cannot be more than 5 in number" # Added expected output
)

# Crew Coordination
twitter_crew = Crew(
    agents=[tweet_agent, trend_agent],
    tasks=[task_tweets, task_trending]
)

# Execute Crew Tasks
result = twitter_crew.kickoff(inputs={"topic": "Agentic System"})
print(result)

from IPython.display import Markdown
Markdown(result)

